// Mocks generated by Mockito 5.1.0 from annotations
// in unit_test_alta/test/menu_api_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:unit_test_alta/services/menu_api.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [MenuApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockMenuApi extends _i1.Mock implements _i2.MenuApi {
  MockMenuApi() {
    _i1.throwOnMissingStub(this);
  }
}
